-- 2026-09-29 — sudah dijalankan di Supabase oleh Mey atas permintaan Owner.
-- Fitur Teh Siap Saji (halaman kasir).
-- Tabel teh_siap_log(cabang_id, jenis 'seduh'|'set', ml, dicatat_oleh, created_at), RLS baca: is_pegawai(); tulis lewat fungsi.
-- status_teh_siap(p_cabang): sisa = 'set' terakhir (atau 0 sebelum catatan pertama) + seduhan sesudahnya
--   - pemakaian teh dari penjualan (resep 'Teh original' x qty) sesudahnya. Sisa TERBAWA ke hari berikutnya.
-- catat_teh_siap(p_cabang, p_jenis, p_ml): kasir cabang / owner mencatat seduhan atau mengatur sisa.
-- Versi lengkap: migration "teh_siap_saji", "teh_siap_mulai_dari_seduhan_pertama", "teh_siap_sisa_terbawa_hari_berikutnya".
-- Tambahan: jenis 'buang' (kurangi ml, mis. teh kemarin basi). Fungsi saldo_teh_siap(p_cabang, p_sampai).
-- status_teh_siap juga mengembalikan sisa_kemarin_ml (saldo saat ganti hari) & buang_hari_ini_ml.
-- (migration "teh_siap_buang")
-- 2026-09-30: catat_sisa_kemarin(p_cabang, p_ml) — isi/ubah sisa teh kemarin langsung dalam ml.
--   Belum ada catatan sebelum hari ini -> 'set' p_ml tepat sebelum ganti hari; sudah ada -> selisihnya
--   dicatat sebagai 'buang' (kalau berkurang) atau 'seduh' sebelum ganti hari (kalau bertambah).
--   (migration "teh_siap_isi_sisa_kemarin")
-- 2026-09-30: status_teh_siap juga mengembalikan rata_per_jam_ml (rata-rata pemakaian per jam buka, 7 hari).
--   Aplikasi memakai laju = max(1 jam terakhir, rata-rata) untuk perkiraan "cukup berapa jam". (migration "teh_siap_rata_per_jam")
